const fs = require('fs');
const file = 'C:/Users/admin_4/.gemini/antigravity/scratch/team_manager/src/app/api/cron-check/route.ts';
let content = fs.readFileSync(file, 'utf8');

const newFunc = [
  'async function runIpStatusReport() {',
  "  console.log('[CRON] Running IP Status Report...');",
  '  try {',
  '    const cronData = await loadCronData();',
  '    const teams = cronData.teams || [];',
  '',
  "    const IP_STATUS_REF = doc(db, 'appData', 'ip_status');",
  '    const snap = await getDoc(IP_STATUS_REF);',
  "    const ipStatus = snap.exists() ? (snap.data().history || {}) : {};",
  '',
  "    const today = new Date().toISOString().split('T')[0];",
  "    const nowStr = new Date().toLocaleString('en-US');",
  '',
  '    const STATUS_LABELS = {',
  "      'RP TEST': '📬 RP TEST', 'SPAM': '🔴 SPAM', 'BOUNCE': '❌ BOUNCE',",
  "      'RDNS': '✅ RDNS', 'PAUSED': '⏸️ PAUSED', 'Change DOM': '🔄 Change DOM',",
  "      'DOWN': '💀 DOWN', 'TO': '⏱️ TO',",
  '    };',
  '',
  "    let msg = '📊 <b>IP STATUS REPORT</b>\\n📅 ' + nowStr + '\\n' + '─'.repeat(28) + '\\n\\n';",
  '    let globalTotal = 0, globalChecked = 0, globalEmpty = 0, globalBounce = 0;',
  '',
  '    for (const team of teams) {',
  "      const activeServers = (team.servers || []).filter((s) => s.status !== 'deleted');",
  '      if (activeServers.length === 0) continue;',
  '',
  '      const teamStats = {};',
  '      let teamTotal = 0, teamEmpty = 0;',
  '',
  '      for (const server of activeServers) {',
  '        const uniqueDomains = getUniqueIpDomains(server.ipDomains);',
  '        const ips = [];',
  '        if (uniqueDomains.length > 0) uniqueDomains.forEach((d) => { if (d.ip) ips.push(d.ip); });',
  '        else if (server.mainIp) ips.push(server.mainIp);',
  '',
  '        for (const ip of ips) {',
  '          teamTotal++; globalTotal++;',
  '          const statusToday = ipStatus[ip] && ipStatus[ip][today];',
  '          if (statusToday) {',
  '            teamStats[statusToday] = (teamStats[statusToday] || 0) + 1;',
  '            globalChecked++;',
  "            if (statusToday === 'BOUNCE') globalBounce++;",
  '          } else { teamEmpty++; globalEmpty++; }',
  '        }',
  '      }',
  '',
  "      msg += '🏢 <b>Team ' + team.name + '</b> — ' + teamTotal + ' IPs\\n';",
  '      const sorted = Object.entries(teamStats).sort((a, b) => b[1] - a[1]);',
  '      if (sorted.length > 0) {',
  '        sorted.forEach(([status, count]) => {',
  '          msg += "  " + (STATUS_LABELS[status] || status) + ": <b>" + count + "</b>\\n";',
  '        });',
  "        if (!teamStats['BOUNCE']) msg += '  ❌ BOUNCE: <b>0</b>\\n';",
  '      } else {',
  "        msg += '  ❌ BOUNCE: <b>0</b>\\n';",
  '      }',
  "      if (teamEmpty > 0) msg += '  ⬜ No Status: <b>' + teamEmpty + '</b>\\n';",
  "      msg += '\\n';",
  '    }',
  '',
  "    msg += '─'.repeat(28) + '\\n';",
  "    msg += '📦 <b>Total IPs:</b> ' + globalTotal + '\\n';",
  "    msg += '✅ <b>With Status:</b> ' + globalChecked + '\\n';",
  "    msg += '❌ <b>Total BOUNCE:</b> ' + globalBounce + '\\n';",
  "    msg += '⬜ <b>No Status Today:</b> ' + globalEmpty + '\\n';",
  '',
  '    await sendTelegramTopic(msg, TELEGRAM_GROUP_ID, TOPIC_IP_STATUS_THREAD_ID);',
  "    console.log('[CRON] IP Status Report sent!');",
  '  } catch (e) {',
  "    console.error('[CRON] IP Status Report error:', e);",
  '  }',
  '}'
].join('\n');

const start = content.indexOf('async function runIpStatusReport()');
const end = content.indexOf('\nexport async function POST', start);
content = content.slice(0, start) + newFunc + '\n' + content.slice(end);
fs.writeFileSync(file, content, 'utf8');
console.log('Done! New func length:', newFunc.length);
